//! Export the OLTP point-read/point-write workload so engines this binary
//! cannot link against — MySQL, PostgreSQL — can be asked the same
//! questions, and measure InlaySQL on it twice.
//!
//! [`points`](crate::points) measures InlaySQL against SQLite in-process,
//! through `rusqlite`. There is nothing on disk for a containerised engine to
//! read: no schema, no rows, no lookup sequence. So [`run`] writes the same
//! fixed inputs the `points` suite already generates from `Config::seed` —
//! the rows to load and the exact sequence of primary keys to look up — to
//! disk once, and measures InlaySQL over those same files, on the host, in
//! the same shape `bench/external/report.py` already merges for the
//! retrieval comparison. `bench/external/mysql_driver.py` and
//! `postgres_oltp_driver.py` read them from `bench/compare.sh`.
//!
//! [`replay`] measures InlaySQL a *second* time, over the identical exported
//! files, but inside the same container network and on the same class of
//! storage volume MySQL and PostgreSQL use for their own data directories —
//! a named Docker volume, not the host filesystem `run`'s measurement uses.
//! `bench/external/compose.yml`'s `inlaysql-oltp` service runs it. See
//! `bench/README.md` for why the two rows exist and what the gap between
//! them means.
//!
//! # What is exported, and why nothing else is
//!
//! * **The rows to load** (`oltp-rows.csv`) — `id 1..=rows`, in that order,
//!   each with the same payload string [`points`] uses. Sequential ids in
//!   ascending order is also the write order every driver is expected to
//!   replay; there is no separate "write sequence" file because the sequence
//!   *is* `1..=rows`.
//! * **The lookup key sequence** (`oltp-lookup-keys.csv`) — generated by
//!   [`points::lookup_keys`], the identical seeded sequence the in-process
//!   SQLite comparison uses, so a driver replays the same questions in the
//!   same order rather than a fresh random draw that happens to have the same
//!   distribution.
//! * **Not the batched-write row.** `points` also measures InlaySQL with many
//!   rows folded into one transaction (one `fsync` per batch instead of per
//!   row) — an InlaySQL-specific number with no natural equivalent on the
//!   other two engines without picking an arbitrary batch size for them too,
//!   which would make the comparison about the chosen batch size rather than
//!   about the engines. Only the per-statement durable write is exported.
//!   See `bench/README.md`.
//!
//! # Durability
//!
//! InlaySQL has one commit mode: every statement here is a durable commit,
//! synced before `execute_prepared` returns. That is deliberately the same
//! shape MySQL and PostgreSQL are configured for in `compose.yml` —
//! `innodb_flush_log_at_trx_commit=1` and `fsync=on` /
//! `synchronous_commit=on` respectively — so the comparison is real
//! durability against real durability. `bench/README.md` documents each
//! engine's setting and states plainly where the match cannot be exact.

use std::fs;
use std::io::Write;
use std::path::Path;
use std::time::{Duration, Instant};

use inlaysql::{Database, Value};

use crate::points::lookup_keys;
use crate::{percentiles, Config};

pub fn run(config: &Config, directory: &Path) -> Result<(), Box<dyn std::error::Error>> {
    fs::create_dir_all(directory)?;
    let rows = config.rows;
    let lookups = config.lookups;
    let payload = "x".repeat(config.payload);
    let keys = lookup_keys(config.seed, rows, lookups);

    write_rows(&directory.join("oltp-rows.csv"), rows, &payload)?;
    write_keys(&directory.join("oltp-lookup-keys.csv"), &keys)?;

    let manifest = format!(
        "{{\n  \"rows\": {rows},\n  \"lookups\": {lookups},\n  \"payload_bytes\": {},\n  \
         \"seed\": {},\n  \
         \"write_order\": \"sequential id 1..=rows, one INSERT per row, one durable commit per row\",\n  \
         \"schema\": \"id INTEGER PRIMARY KEY, body TEXT\"\n}}\n",
        config.payload, config.seed,
    );
    fs::write(directory.join("oltp-manifest.json"), manifest)?;

    // InlaySQL's own numbers, on the host, over the exact files the
    // containerised drivers read, written in the shape `report.py` merges.
    // This is the *reference* row: InlaySQL's own commit path, `F_FULLFSYNC`
    // (or the platform equivalent) all the way to the host disk — the same
    // promise the `points` suite's InlaySQL row makes.
    let owned_rows: Vec<(i64, String)> =
        (1..=rows as i64).map(|id| (id, payload.clone())).collect();
    let db_path = std::path::Path::new("target").join("bench-oltp-export.inlay");
    let result = measure_inlaysql(
        &db_path,
        &owned_rows,
        &keys,
        "InlaySQL",
        "in-process, no server, so this number pays no client/server round trip the MySQL/ \
         PostgreSQL rows do; one durable commit per statement (no batching), matched to \
         MySQL's innodb_flush_log_at_trx_commit=1 and PostgreSQL's fsync=on / \
         synchronous_commit=on rows here; measured on the host filesystem, so its fsync is \
         whatever barrier the host honours — see bench/README.md for the full durability \
         rationale, the containerised row below it, and the asymmetries that remain",
    )?;
    fs::write(directory.join("results-oltp-inlaysql.json"), result)?;

    println!(
        "wrote the OLTP workload ({rows} rows, {lookups} lookups) to {}",
        directory.display()
    );
    println!("run bench/compare.sh to measure MySQL, PostgreSQL and containerised InlaySQL on the same files");
    Ok(())
}

/// Replay the exported OLTP workload against InlaySQL a second time, inside
/// a container, on the same class of storage volume MySQL and PostgreSQL use
/// for their own data directories — a named Docker volume, not the corpus
/// bind mount `directory` is, and not the host filesystem [`run`]'s
/// measurement uses.
///
/// `directory` is where [`run`] wrote the exported workload
/// (`oltp-rows.csv`, `oltp-lookup-keys.csv`) — the corpus bind mount, shared
/// read-only-in-spirit with the MySQL/PostgreSQL drivers — and where the
/// result (`results-oltp-inlaysql-container.json`) lands so `report.py`
/// merges it the same way. `db_path` is where the database file this run
/// creates and fsyncs actually lives, and it is the entire point of this
/// function: `bench/external/compose.yml`'s `inlaysql-oltp` service points
/// it at a named Docker volume, the same class as `postgres-oltp-data` and
/// `mysql-oltp-data`, specifically so this row's `fsync` crosses the same
/// virtualised-disk boundary theirs does. See `bench/README.md`.
pub fn replay(directory: &Path, db_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let rows = read_rows(&directory.join("oltp-rows.csv"))?;
    let keys = read_keys(&directory.join("oltp-lookup-keys.csv"))?;

    let result = measure_inlaysql(
        db_path,
        &rows,
        &keys,
        "InlaySQL (containerised, same volume class as MySQL/PostgreSQL)",
        "runs inside the same compose network and off the same docker/Dockerfile image as \
         MySQL and PostgreSQL, and its database file lives on a named Docker volume like \
         theirs rather than a host bind mount, so its fsync crosses the same virtualised-disk \
         boundary theirs does; still in-process, so it pays no client/server round trip — that \
         asymmetry is structural and remains. Compare against the host InlaySQL row to see \
         what the virtualised fsync itself costs on this machine — see bench/README.md",
    )?;
    fs::write(
        directory.join("results-oltp-inlaysql-container.json"),
        result,
    )?;

    println!(
        "wrote the containerised InlaySQL OLTP result to {}",
        directory.display()
    );
    Ok(())
}

fn write_rows(path: &Path, rows: usize, payload: &str) -> std::io::Result<()> {
    let mut file = std::io::BufWriter::new(fs::File::create(path)?);
    writeln!(file, "id,body")?;
    for id in 1..=rows {
        writeln!(file, "{id},{payload}")?;
    }
    file.flush()
}

fn write_keys(path: &Path, keys: &[i64]) -> std::io::Result<()> {
    let mut file = std::io::BufWriter::new(fs::File::create(path)?);
    writeln!(file, "idx,key")?;
    for (idx, key) in keys.iter().enumerate() {
        writeln!(file, "{idx},{key}")?;
    }
    file.flush()
}

/// Read `oltp-rows.csv` back exactly as written by [`write_rows`]: an
/// `id,body` header followed by one row per line, no quoting needed because
/// the payload is a plain repeated character with no commas in it — the same
/// assumption `bench/external/common.py`'s `load_oltp` makes on the Python
/// side.
fn read_rows(path: &Path) -> Result<Vec<(i64, String)>, Box<dyn std::error::Error>> {
    let content = fs::read_to_string(path)?;
    let mut rows = Vec::new();
    for line in content.lines().skip(1) {
        if line.is_empty() {
            continue;
        }
        let (id, body) = line
            .split_once(',')
            .ok_or_else(|| format!("malformed row in {}: {line:?}", path.display()))?;
        rows.push((id.parse::<i64>()?, body.to_string()));
    }
    Ok(rows)
}

/// Read `oltp-lookup-keys.csv` back exactly as written by [`write_keys`].
fn read_keys(path: &Path) -> Result<Vec<i64>, Box<dyn std::error::Error>> {
    let content = fs::read_to_string(path)?;
    let mut keys = Vec::new();
    for line in content.lines().skip(1) {
        if line.is_empty() {
            continue;
        }
        let (_, key) = line
            .split_once(',')
            .ok_or_else(|| format!("malformed row in {}: {line:?}", path.display()))?;
        keys.push(key.parse::<i64>()?);
    }
    Ok(keys)
}

/// InlaySQL's own numbers over the exported workload: prepared statements,
/// one durable commit per write, the identical lookup-key sequence — the
/// same methodology [`points::run`] uses for the in-process SQLite
/// comparison. Shared by [`run`] (host filesystem) and [`replay`]
/// (containerised, named volume); only where `db_path` lives differs.
fn measure_inlaysql(
    db_path: &Path,
    rows: &[(i64, String)],
    keys: &[i64],
    engine: &str,
    notes: &str,
) -> Result<String, Box<dyn std::error::Error>> {
    if let Some(parent) = db_path.parent() {
        fs::create_dir_all(parent)?;
    }
    let _ = fs::remove_file(db_path);
    let mut db = Database::open(db_path)?;
    db.execute("CREATE TABLE kv (id INTEGER PRIMARY KEY, body TEXT)", &[])?;

    // Prepared outside the timed loops, matching the `points` suite and the
    // MySQL/PostgreSQL drivers, which prepare their statements once too.
    let insert = db.prepare("INSERT INTO kv (id, body) VALUES (?, ?)")?;
    let lookup = db.prepare("SELECT body FROM kv WHERE id = ?")?;

    let mut writes = Vec::with_capacity(rows.len());
    let started = Instant::now();
    for (id, body) in rows {
        let at = Instant::now();
        db.execute_prepared(
            &insert,
            &[Value::Integer(*id), Value::Text(body.clone().into())],
        )?;
        writes.push(at.elapsed());
    }
    let write_elapsed = started.elapsed();

    let mut reads = Vec::with_capacity(keys.len());
    let started = Instant::now();
    for key in keys {
        let at = Instant::now();
        let result = db.query_prepared(&lookup, &[Value::Integer(*key)])?;
        debug_assert_eq!(result.rows.len(), 1, "point read missed row {key}");
        reads.push(at.elapsed());
    }
    let read_elapsed = started.elapsed();

    let _ = fs::remove_file(db_path);
    Ok(oltp_result_json(
        engine,
        rows.len(),
        keys.len(),
        write_elapsed,
        &writes,
        read_elapsed,
        &reads,
        notes,
    ))
}

/// The result shape every OLTP driver writes, so `report.py` can merge them
/// without knowing which engine produced which file. Sibling to
/// [`crate::export::result_json`] (vector/hybrid, for the retrieval
/// comparison) rather than a reuse of it: this workload measures reads and
/// writes, not recall and agreement, so the fields differ, but the idea is
/// the same — one process's numbers, in a shape any driver can produce.
#[allow(clippy::too_many_arguments)]
fn oltp_result_json(
    engine: &str,
    rows: usize,
    lookups: usize,
    write_elapsed: Duration,
    write_samples: &[Duration],
    read_elapsed: Duration,
    read_samples: &[Duration],
    notes: &str,
) -> String {
    let (wp50, wp95, wmax) = percentiles(write_samples);
    let (rp50, rp95, rmax) = percentiles(read_samples);
    let ms = |d: Duration| d.as_secs_f64() * 1000.0;
    let ops_s =
        |count: usize, elapsed: Duration| count as f64 / elapsed.as_secs_f64().max(f64::EPSILON);
    format!(
        "{{\n  \"engine\": \"{engine}\",\n  \"rows\": {rows},\n  \"lookups\": {lookups},\n  \
         \"write\": {{\"ops_s\": {:.1}, \"p50_ms\": {:.3}, \"p95_ms\": {:.3}, \"max_ms\": {:.3}}},\n  \
         \"read\": {{\"ops_s\": {:.1}, \"p50_ms\": {:.3}, \"p95_ms\": {:.3}, \"max_ms\": {:.3}}},\n  \
         \"notes\": \"{notes}\"\n}}\n",
        ops_s(rows, write_elapsed),
        ms(wp50),
        ms(wp95),
        ms(wmax),
        ops_s(lookups, read_elapsed),
        ms(rp50),
        ms(rp95),
        ms(rmax),
    )
}
