[package]
name = "inlaysql-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
inlaysql-core = { path = "../crates/inlaysql-core" }
arbitrary = { version = "1", features = ["derive"] }

[[bin]]
name = "sql_parser"
path = "fuzz_targets/sql_parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "storage"
path = "fuzz_targets/storage.rs"
test = false
doc = false
bench = false

[[bin]]
name = "row_codec"
path = "fuzz_targets/row_codec.rs"
test = false
doc = false
bench = false

[[bin]]
name = "json_parser"
path = "fuzz_targets/json_parser.rs"
test = false
doc = false
bench = false
